from app.models.user import User
from app.models.course import Course
from app.models.material import Material
from app.models.material_chunk import MaterialChunk
from app.models.chat_session import ChatSession
from app.models.chat_message import ChatMessage
from app.models.task import Task
from app.models.study_plan import StudyPlan
from app.models.study_plan_task import StudyPlanTask
from app.models.note import Note
from app.models.note_sync_record import NoteSyncRecord
from app.models.learning_record import LearningRecord
from app.models.course_progress import CourseProgress